version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=ecotrack
      - DB_USER=ecotrack_user
      - DB_PASSWORD=ecotrack_password

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=ecotrack_user
      - POSTGRES_PASSWORD=ecotrack_password
      - POSTGRES_DB=ecotrack
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"