version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: wellness_user
      POSTGRES_PASSWORD: wellness_password
      POSTGRES_DB: wellness_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wellness_api
    environment:
      ENV_TYPE: development
      SERVER_PORT: 8080
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wellness_user
      DB_PASSWORD: wellness_password
      DB_NAME: wellness_db
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: