  const appContainer = document.getElementById('app');
  const inputContainer = document.createElement('div');
  const activityInput = document.createElement('input');
  activityInput.type = 'text';
  activityInput.id = 'activity-input';
  activityInput.placeholder = 'Enter your activity';
  inputContainer.appendChild(activityInput);
  const trackButton = document.createElement('button');
  trackButton.id = 'track-btn';
  trackButton.textContent = 'Track Activity';
  inputContainer.appendChild(trackButton);
  appContainer.appendChild(inputContainer);
  const emissionsContainer = document.createElement('div');
  emissionsContainer.id = 'emissions';
  appContainer.appendChild(emissionsContainer);
  const tipsContainer = document.createElement('ul');
  tipsContainer.id = 'eco-tips';
  appContainer.appendChild(tipsContainer);